### ISSUE TITLE
Library fails to resolve/process requests after some time.

### ISSUE THREAD

**Issue by Synkstar** [timschumi/gmod-chttp#9] opened 2020-06-22 02:47 UTC
This is pretty strange ? Would anyone know how I could fix this ?

**Comment by Synkstar** [comment] 2020-06-22 05:59
Also I think the updated broke lots of stuff because my server is seg faulting randomly lmao

**Comment by timschumi** [comment] 2020-06-22 10:51
> I get could not resolve hostname errors after its running for awhile

This is quite certainly an issue with your network connection. Or at least there is nothing in this module that would cause that error specifically. Your server simply couldn't reach it's domain server, so it has no idea where to send the HTTP request to.

> Also I think the updated broke lots of stuff because my server is seg faulting randomly

The only thing that the update did was to fix a crash. Also, wasn't your server segfaulting randomly before?

Anyways, unless you can give me more information (for example the list of installed addons) and a [backtrace](https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_42.html) of the crash [in GDB](https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_22.html) (preferably with the debug version of the library), I can't do much regarding this. If you can obtain that information, please open a new issue.

I am hoping that I can implement better logging at some point, but that will still take a while (due to having to make SourceSDK compatible with x64).

> lmao

What are you, a 12 year old child?

**Comment by Synkstar** [comment] 2020-06-22 18:31
It did stop segfaulting when I removed it and It Billys logs says that there is malformed data(Only when its install). I am using pterodactyl panel so the servers run under a docker container I tried attaching gdb but inside the container it doesn't work even as root because containers from pterodactyl have debugging disabled.

**Comment by Synkstar** [comment] 2020-06-22 18:36
Also I know its not only my server because other servers using that Discord relay(That used CHTTP) from gmodstore are not working.

**Comment by Synkstar** [comment] 2020-06-22 18:38
Also sorry for using "lmao" it was late and this is like a serious matter because other people are having issues aswell. But CHTTP is a good module its just that C++ binarys are very picky and can crash the server with a segfault + a gmod update that changes something could break some stuff.

**Comment by timschumi** [comment] 2020-06-22 20:35
> It did stop segfaulting when I removed it and It Billys logs says that there is malformed data(Only when its install).

Do the segfaults stop if you remove Billy's logs?

> I am using pterodactyl panel so the servers run under a docker container I tried attaching gdb but inside the container it doesn't work even as root because containers from pterodactyl have debugging disabled.

Run the server bare-metal then, or get someone else to do it (I've never heard of Docker containers disabling debugging, but I might be wrong). I can't do any debugging because you aren't sharing any details about your setup, and if it's indeed caused by Billy's logs, I have no access to that addon.

> Also I know its not only my server because other servers using that Discord relay(That used CHTTP) from gmodstore are not working.

The other person (that I fixed a segfault for) doesn't appear to have any issues anymore. I can't see anything on the GModStore page either that indicates that others are having issues.

> C++ binarys are very picky and can crash the server with a segfault

Usually nothing that can't be fixed though.

> a gmod update that changes something could break some stuff.

The API has been stable for quite some time and everything links dynamically.

**Comment by Synkstar** [comment] 2020-06-22 21:16
I got rid of blogs and the server was still segfaulting. The segfaults only stopped when I removed the module

**Comment by Synkstar** [comment] 2020-06-22 21:29
Ok actually what I can do is run it as root outside of the container and do the debug that should work. Just give me a minute

**Comment by Synkstar** [comment] 2020-06-22 21:47
Yeah I dont think I can do this because when I attach to the process wether its running as root or another user it locks up the server and when I detach it closes

**Comment by timschumi** [comment] 2020-06-22 21:53
GDB (or rather, Garry's Mod) interrupts when a debugger is attached, and has a few debugger interrupts throughout the program. Whenever the server locks up, check the gdb console whether it's an actual exception or just an interrupt. If it's an interrupt, you can put in the `c` command to make GDB continue the process.

**Comment by Synkstar** [comment] 2020-06-22 22:11
`CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Could not find steamerrorreporter binary. Any minidumps will be uploaded in-processapplicationmanager.cpp (3936) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
applicationmanager.cpp (3936) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
Uploading dump (in-process) [proxy '']
/tmp/dumps/crash_20200622180710_5.dmp
`
When I put the gdb module in I didnt even attach to the process and it freezes up and near the top I see that.

[crash_20200622142007_5.zip](https://github.com/timschumi/gmod-chttp/files/4815810/crash_20200622142007_5.zip)

**Comment by Synkstar** [comment] 2020-06-22 22:18
Actually nvm thats something different it doesnt even want to start from outside a docker container. I pterodactyl panel servers arent really designed for use as a debugging environment. Unless I can figure out how pterodactyl starts the containers and start it in my terminal with a line that enables the debugging

**Comment by timschumi** [comment] 2020-06-22 22:29
I mean, what happens if you try to install and attach gdb inside the container? You can open a root shell by running `docker exec -it -u 0 <container id> /bin/bash` on the server. From there, you should be able to install GDB (`apt install gdb`) and attach to the process as outlined before.

**Comment by Synkstar** [comment] 2020-06-22 22:30
``
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
attach: No such file or directory.
Attaching to process 40
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
/home/container/40: No such file or directory.
``

**Comment by Synkstar** [comment] 2020-06-22 22:32
Actually I have an idea I will try adding a line that changes that value to the install script of the container then rebuild it 1 sec

**Comment by Synkstar** [comment] 2020-06-22 22:33
Actually it says its enabled so idk

**Comment by timschumi** [comment] 2020-06-24 13:00
The issue was caused by the library neither joining nor detaching threads after creating them. Therefore, threads were kept allocated, even though they already stopped running. Eventually, pthread_create would fail with `EAGAIN` (error code 11) and the remaining request queue would not be processed. Another symptom would be that curl was not able to resolve the hosts it should request to (`Couldn't resolve host name`), since that is multithreaded internally.

**Comment by timschumi** [comment] 2020-06-24 13:01
Fixed in v1.3.2 (ee9248d).

**Closed by timschumi** 2020-06-24 13:01 UTC
Labels: bug, linux
