### ISSUE TITLE
"Couldn't load module library" on CentOS 7

### ISSUE THREAD

**Issue by Yufukuai** [timschumi/gmod-chttp#12] opened 2020-08-28 22:29 UTC
Hey, I want to open an issue since I have an issue with cHTTP and the addon Billy's Logs which is a paid addon of gmodstore.com that works with cHTTP for making Discord webhooks work with the logs.

And the issue is that I can't share any private code without the author permission.

The issue happens when cHTTP is present, when is not, the addon starts just fine, but when it is present it throws a lot of lua errors. I told the developer about this issue and he said that it was issue with cHTTP that it's broken.

If you need more info I would be very happy to provide it, but I can't share private code

**Comment by timschumi** [comment] 2020-08-28 22:42
> And the issue is that I can't share any private code without the author permission.

I don't expect you to. In case we'd have to resort to the addon source code (or generally, insight into the addon) we can still CC the addon creator.

> 
> The issue happens when cHTTP is present, when is not, the addon starts just fine, but when it is present it throws a lot of lua errors. I told the developer about this issue and he said that it was issue with cHTTP that it's broken.

I'm not aware of any regressions in the newest version of CHTTP, but could you test an older version just in case? A screenshot of those errors might help a lot as well. Also, you might want to try loading the library manually (by running `lua_run require("chttp")` in the server console) and seeing whether that succeeds (preferably without Billy's Logs installed/enabled to keep the output clean).

**Comment by Yufukuai** [comment] 2020-08-28 22:51
> require("chttp")...

[ERROR] lua_run:1: Couldn't load module library!
  1. require - [C]:-1
   2. unknown - lua_run:1

This is the output

**Comment by timschumi** [comment] 2020-08-28 22:59
What OS, distribution, and (especially) version is the server running on? I'm going to assume that it's CentOS 7 or something that's equally old.

**Comment by Yufukuai** [comment] 2020-08-28 23:08
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 5.4.34-1-pve
Architecture: x86-64

Server running in Docker

**Comment by timschumi** [comment] 2020-08-28 23:40
Yeah, that's... old. So old in fact that I haven't found a compatible way to build the module without upgrading what feels like half of the system manually. The basic problem is that the glibc used by CentOS 7 is too old compared to the glibc of the system that I'm building this on.

If possible, try to update your Docker container to a different (newer) base. Meanwhile, I'll try and find out whether the compiler that is shipped with CentOS 7 even supports C++11.

At some point, I'll hopefully be able to figure out how to build using the Steam Runtime, and whether it is of any use.

**Comment by timschumi** [comment] 2020-08-29 00:43
I managed to get _something_ to build, but I'm not sure if those even load, even less whether they have all the required functionality.

Let me know if these work.

[chttp-1.4.0-rc1-centos7.zip](https://github.com/timschumi/gmod-chttp/files/5144562/chttp-1.4.0-rc1-centos7.zip)

**Comment by Yufukuai** [comment] 2020-08-29 00:44
I asked the host to update the OS, I'm backing up everything. (I'm going to update to CentOS 8)

**Comment by Yufukuai** [comment] 2020-08-29 00:45
But I could try now, if you want to, but I will end updating to CentOS 8

**Comment by timschumi** [comment] 2020-08-29 00:48
Would be awesome if you can test it, since this wasn't the first time I have seen someone having problems with CentOS 7, and it probably won't be the last time either. Having some known-good libraries that I can link to would be nice.

**Comment by Yufukuai** [comment] 2020-08-29 01:32
require("chttp")... No errors.

**Comment by Yufukuai** [comment] 2020-08-29 16:50
It's fixed, the build that you made works with CentOS 7, this can help those users that their hosts still use CentOS 7 instead of CentOS 8.

**Comment by timschumi** [comment] 2020-08-30 01:48
Awesome! I'll still keep this open though since more people can see it then and so that I eventually get around to making the main builds compatible.

**Comment by timschumi** [comment] 2021-03-21 19:52
I have now released version 1.4.1, which uses an older build target (Debian 8) and provides additional `-static` builds that have their `libstdc++` and `libgcc` included in the binary (`libstdc++` was the main reason why the library wouldn't load on CentOS 7).

Since the "compatibility builds" are no longer hand-crafted, I feel like we can close this now, even if it's not the "default build" that is compatible.

**Closed by timschumi** 2021-03-21 19:52 UTC
Labels: installation issue, linux
